QueryBase/Areas/Users/Controllers/AskQuestionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using QueryBase.DataAccess.Repository.IRepository;
using QueryBase.Models;
using QueryBase.Models.ViewModels;
using System.Security.Claims;
using System.Text.Json.Nodes;

namespace QueryBase.Areas.Users.Controllers
{
    [Area("Users")]
    public class AskQuestionController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUnitOfWork _unitOfWork;
        public AskQuestionController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Ask()
        {

            var askQuestionVM = new AskQuestionVM()
            {
                CategoryList = _unitOfWork.CategoryRepository.GetAll().Select( cl => new SelectListItem()
                {
                    Text = cl.CategoryName,
                    Value = cl.Id.ToString(),
                })
            };
            return View(askQuestionVM);
        }

        [HttpPost]
        public IActionResult Ask(AskQuestionVM askQuestionVM)
        {
            if (!ModelState.IsValid)
            {
                askQuestionVM.CategoryList = _unitOfWork.CategoryRepository.GetAll().Select(cl => new SelectListItem()
                {
                    Text= cl.CategoryName,
                    Value = cl.Id.ToString(),
                });
                return View(askQuestionVM);
            }

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            Question question = new Question()
            {
                Id = Guid.NewGuid(),
                Description = askQuestionVM.Description,
                Title = askQuestionVM.Title,
                CategoryId = askQuestionVM.CategoryId,
                UserId = Guid.Parse(userId),
                AnswerCount = 0,
                ViewsCount = 0,
                VotesCount = 0,
                PostedDateAndTime = DateTime.UtcNow,
                ModifiedDateAndTime = DateTime.UtcNow
            };
            _unitOfWork.QuestionRepository.Add(question);
            _unitOfWork.Save();
            return RedirectToAction(nameof(HomeController.Index), "Home", new { area = "Users" });
        }







        #region API CALLS

        [HttpPost]
        public IActionResult UploadImage(IFormFile? upload)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            if (upload != null)
            {
                if(upload.Length > 1 * 1024 * 1024)
                {
                    return Json(new {error = new {message = "The image upload failed because the image was too big (max 1MB)." } });
                }

                string imagePath = Path.Combine(webRootPath, @"images");
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);

                //checking if the same name file exists
                while (System.IO.File.Exists(Path.Combine(imagePath, fileName)))
                {
                    fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);
                }
                string fullPath = Path.Combine(imagePath, fileName);
                //creating the file
                using (var fileStream = new FileStream(fullPath, FileMode.Create))
                {
                    upload.CopyTo(fileStream);
                }

                //checking if file is created 
                if(System.IO.File.Exists(fullPath))
                {
                    return Json(new {url = "/images/" + fileName});
                }
                else
                {
                    return Json(new { error = new { message = "Image upload failed, please try again." } });
                }
            }
            else
            {
                return Json(new { error = new { message = "Image upload failed, please try again." } });
            }
        }

        [HttpPost]
        public IActionResult DeleteImage(string imagePath)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            if (!imagePath.IsNullOrEmpty())
            {
                string fullPath = Path.Combine(webRootPath, imagePath.TrimStart('/'));
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                return Json(new {success = true});
            }
            else
            {
                return Json(new {success = false});
            }
        }

        [HttpPost]
        public IActionResult DeleteUnsavedImages([FromBody]UnsavedImagesListVM unsavedImagesListVM)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            foreach(string imagePath in unsavedImagesListVM.unsavedImages)
            {
                string fullPath = Path.Combine(webRootPath, imagePath.TrimStart('/'));
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
            }
            return Ok();
        }

        #endregion
    }

}

QueryBase/Areas/Users/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QueryBase.DataAccess.Repository.IRepository;
using QueryBase.Models;
using System.Diagnostics;

namespace QueryBase.Areas.Users.Controllers
{
    [Area("Users")]
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Question> questions = _unitOfWork.QuestionRepository.GetAll(includeProperties: "Category,User").ToList();
            return View(questions);
        }

        //public IActionResult Index(string? search,)
        //{

        //    return View();
        //}

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QueryBase/Areas/Users/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using QueryBase.DataAccess.Repository.IRepository;
using QueryBase.Models.ViewModels;

namespace QueryBase.Areas.Users.Controllers
{
    [Area("Users")]
    public class QuestionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public QuestionController(IUnitOfWork unitOfWork)
        {
             _unitOfWork = unitOfWork;
        }
        public IActionResult Index(Guid questionId)
        {
            var questionVM = new QuestionVM
            {
                Question = _unitOfWork.QuestionRepository.Get(q => q.Id == questionId, includeProperties: "User,Category"),
                Answers = _unitOfWork.AnswerRepository.GetAll(a => a.QuestionId == questionId, includeProperties: "User").ToList()
            };
            return View(questionVM);
        }
    }
}

QueryBase/Areas/Users/Views/Home/Index.cshtml
@model List<Question>
@{
    ViewData["Title"] = "Home Page";
}

<div class="py-4 px-3">
    <div class="d-flex">
        <div class="mb-4 flex-grow-1">
            <h3>Top Questions</h3>
        </div>
        <div class="ms-3">
            <a asp-action="Ask" asp-controller="AskQuestion" asp-area="Users" class="btn btn-info">Ask Question</a>
        </div>
    </div>

    <div class="border-top border-1">
        <div class="mb-5">
            <div>
                @foreach(var question in Model)
                { 
                    var time = DateTime.Now - question.ModifiedDateAndTime;
                    
                    <div class="p-3 border-bottom border-1 d-flex flex-column flex-md-row ">
                        <div id="stat-box" class="fs-small stat-box me-3 mb-1 d-flex flex-row gap-2 flex-wrap flex-md-column row-gap-md-2 flex-md-nowrap">
                        <div class="d-flex flex-row column-gap-1 justify-content-end">
                            <div>@question.VotesCount</div>
                            <div>votes</div>
                        </div>
                        <div class="text-muted d-flex flex-row column-gap-1 justify-content-end">
                            <div>@question.AnswerCount</div>
                            <div>answers</div>
                        </div>
                        <div class="text-muted d-flex flex-row column-gap-1 justify-content-end">
                            <div>@question.ViewsCount</div>
                            <div>views</div>
                        </div>
                    </div>
                    <div class="flex-grow-1">
                        <div class="mb-2">
                            <a asp-area="Users" asp-controller="Question" asp-action="Index" asp-route-questionId="@question.Id" class="text-break fs-5 pe-4 link text-decoration-none">@question.Title</a>
                        </div>
                        <div class="d-flex gap-2 fs-small flex-wrap">
                            <div class="me-1 mb-1">
                                <div class="fw-bolder bg-body-secondary px-1 lh-lg">
                                    <a class=" text-decoration-none text-body">@question.Category.CategoryName</a>
                                </div>
                            </div>
                            <div class="flex-grow-1 lh-lg">
                                <div class="d-flex justify-content-end gap-1 flex-warp">
                                    <div class="px-1">
                                        <a class="link text-decoration-none">@question.User.UserName</a>
                                    </div>
                                    <div class="px-1">
                                            modified @if(time.Days > 0)
                                            {
                                                <span>@time.Days days ago</span>
                                            }
                                            else if(time.Hours > 0){
                                                <span>@time.Hours hours ago</span>
                                            }
                                            else if(time.Minutes > 0)
                                            {
                                                <span>@time.Minutes minutes ago</span>
                                            }
                                            else
                                            {
                                                <span>@time.Seconds seconds ago</span>
                                            }
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
                }
            </div>
        </div>
    </div>
</div>