QueryBase/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using QueryBase.DataAccess.Repository.IRepository;
using QueryBase.Models;
using QueryBase.Models.ViewModels;

namespace QueryBase.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            CategoryPageVM categoryPageVM = new CategoryPageVM()
            {
                Categories = _unitOfWork.CategoryRepository.GetAll().ToList()
            };
            return View(categoryPageVM);
        }

        [HttpPost]
        public IActionResult Create(CategoryVM categoryVM)
        {
            Category category = new Category()
            {
                Id = Guid.NewGuid(),
                CategoryName = categoryVM.CategoryName
            };
            _unitOfWork.CategoryRepository.Add(category);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(Guid Id)
        {
            _unitOfWork.CategoryRepository.Remove(_unitOfWork.CategoryRepository.Get(c => c.Id == Id));
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Edit(CategoryVM categoryVM)
        {
            Category category = _unitOfWork.CategoryRepository.Get(c => c.Id == categoryVM.Id);
            category.CategoryName = categoryVM.CategoryName;
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

QueryBase/Areas/Users/Controllers/AskQuestionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using QueryBase.DataAccess.Repository.IRepository;
using QueryBase.Models;
using QueryBase.Models.ViewModels;
using System.Security.Claims;
using System.Text.Json.Nodes;

namespace QueryBase.Areas.Users.Controllers
{
    [Area("Users")]
    public class AskQuestionController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUnitOfWork _unitOfWork;
        public AskQuestionController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Ask()
        {

            var askQuestionVM = new AskQuestionVM()
            {
                CategoryList = _unitOfWork.CategoryRepository.GetAll().Select( cl => new SelectListItem()
                {
                    Text = cl.CategoryName,
                    Value = cl.Id.ToString(),
                })
            };
            return View(askQuestionVM);
        }

        [HttpPost]
        public IActionResult Ask(AskQuestionVM askQuestionVM)
        {
            if (!ModelState.IsValid)
            {
                askQuestionVM.CategoryList = _unitOfWork.CategoryRepository.GetAll().Select(cl => new SelectListItem()
                {
                    Text= cl.CategoryName,
                    Value = cl.Id.ToString(),
                });
                return View(askQuestionVM);
            }

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            Question question = new Question()
            {
                Id = Guid.NewGuid(),
                Description = askQuestionVM.Description,
                Title = askQuestionVM.Title,
                CategoryId = askQuestionVM.CategoryId,
                UserId = Guid.Parse(userId),
                AnswerCount = 0,
                ViewsCount = 0,
                VotesCount = 0,
                PostedDateAndTime = DateTime.UtcNow,
                ModifiedDateAndTime = DateTime.UtcNow
            };
            _unitOfWork.QuestionRepository.Add(question);
            _unitOfWork.Save();
            return RedirectToAction(nameof(HomeController.Index), "Home", new { area = "Users" });
        }







        #region API CALLS

        [HttpPost]
        public IActionResult UploadImage(IFormFile? upload)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            if (upload != null)
            {
                if(upload.Length > 1 * 1024 * 1024)
                {
                    return Json(new {error = new {message = "The image upload failed because the image was too big (max 1MB)." } });
                }

                string imagePath = Path.Combine(webRootPath, @"images");
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);

                //checking if the same name file exists
                while (System.IO.File.Exists(Path.Combine(imagePath, fileName)))
                {
                    fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);
                }
                string fullPath = Path.Combine(imagePath, fileName);
                //creating the file
                using (var fileStream = new FileStream(fullPath, FileMode.Create))
                {
                    upload.CopyTo(fileStream);
                }

                //checking if file is created 
                if(System.IO.File.Exists(fullPath))
                {
                    return Json(new {url = "/images/" + fileName});
                }
                else
                {
                    return Json(new { error = new { message = "Image upload failed, please try again." } });
                }
            }
            else
            {
                return Json(new { error = new { message = "Image upload failed, please try again." } });
            }
        }

        [HttpPost]
        public IActionResult DeleteImage(string imagePath)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            if (!imagePath.IsNullOrEmpty())
            {
                string fullPath = Path.Combine(webRootPath, imagePath.TrimStart('/'));
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                return Json(new {success = true});
            }
            else
            {
                return Json(new {success = false});
            }
        }

        [HttpPost]
        public IActionResult DeleteUnsavedImages([FromBody]UnsavedImagesListVM unsavedImagesListVM)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            foreach(string imagePath in unsavedImagesListVM.unsavedImages)
            {
                string fullPath = Path.Combine(webRootPath, imagePath.TrimStart('/'));
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
            }
            return Ok();
        }

        #endregion
    }

}

QueryBase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QueryBase</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/flatly/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QueryBase.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ckeditor5.css">
    <link rel="stylesheet" href="~/css/ckeditor5Editor.css" asp-append-version="true" />
</head>
<body >
    <header>

        <nav class="navbar navbar-expand-lg bg-primary sticky-top" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Users" asp-controller="Home" asp-action="Index">QueryBase</a>
                <ul class="navbar-nav me-auto d-block d-lg-none d-flex flex-row">
                    <li class="nav-item">
                        <div class="vr h-100 mx-2 text-white"></div>
                    </li>
                    <li class="nav-item">
                        <div class="d-flex ps-2 form-check form-switch">
                            <input class="mx-1 align-self-center form-check-input" role="button" type="checkbox" id="themeButton" onclick="handleThemeButtonClick()">
                            <label class="px-1 pt-1 mt-2 nav-link form-check-label" role="button" href="#" id="themeLabel" onclick="handleThemeLabelClick()"></label>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"]?.ToString() == "Home" ? "active":"")" asp-area="Users" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Users" asp-action="Ask" asp-controller="AskQuestion">Ask a Question</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-action="Index" asp-controller="Category">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="about" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                        <li class="nav-item py-2 py-lg-1">
                            <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                            <hr class="d-lg-none my-2 text-white-50" />
                        </li>
                        <li class="nav-item d-none d-lg-block">
                            <div class="d-flex ps-2 form-check form-switch">
                                <input class="mx-1 align-self-center form-check-input" role="button" type="checkbox" id="md-themeButton" onclick="handleMDThemeButtonClick()">
                                <label class="px-1 nav-link form-check-label" role="button" href="#" id="md-themeLabel" onclick="handleThemeLabelClick()"></label>
                            </div>
                        </li>




                    </ul>

                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>




        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="User" asp-controller="Home" asp-action="Index">QueryBase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="User" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-controller="Register" asp-action="Index">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
    </header>
    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary" data-bs-theme="dark">
        <div class="container">
            &copy; 2024 - QueryBase - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="link">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/themeToggle.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>